name: Test, Lint, Build, e2e on Pull Request to Master

on:
  pull_request:
    branches:
      - master

env:
  CI: true

# env: # https://stackoverflow.com/questions/59867124/how-can-i-access-github-action-environment-variables-within-a-bash-script-run-by
#   STATUS: failing
#   SHA: ${{ github.sha }}
#   BRANCH: ${{ github.ref }}
#   YELLR_KEY: ${{ secrets.YELLR_KEY }}
#   YELLR_URL: ${{ secrets.YELLR_URL }}
#   NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          git fetch --no-tags --prune --depth=5 origin master
      - name: Use Node.js v12
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Application
        run: npm run affected:build -- --base=origin/master --parallel
      # - name: The job has failed
      #   if: failure()
      #   run: ./post_build_results_ga.sh
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          git fetch --no-tags --prune --depth=5 origin master
      - name: Use Node.js v12
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        # https://github.com/actions/cache/issues/193
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Stylelint
        run: npm run stylelint:ci
      - name: Lint
        run: npm run affected:lint -- --base=origin/master --parallel
      # - name: The job has failed
      #   if: failure()
      #   run: ./post_build_results_ga.sh
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          git fetch --no-tags --prune --depth=5 origin master
      - name: Use Node.js v12
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        # https://github.com/actions/cache/issues/193
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: npm run affected:test -- --base=origin/master~1 --parallel --bail=1
      # - name: The job has failed
      #   if: failure()
      #   run: ./post_build_results_ga.sh
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          git fetch --no-tags --prune --depth=5 origin master
      - name: Use Node.js v12
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Cypress
        if: steps.npm-cache.outputs.cache-hit == 'true'
        run: npm i cypress@latest --save-dev
      - name: Test
        run: npm run affected:e2e -- --base=origin/master~1 --headless --parallel
  # - name: The job has failed
  #   if: failure()
  #   run: ./post_build_results_ga.sh
  # post_results:
  #   name: Post Results
  #   runs-on: ubuntu-latest
  #   needs: [test, lint, e2e, build]
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #     - name: Echo Results
  #       env:
  #         STATUS: passing
  #       run: ./post_build_results_ga.sh
